### ISSUE TITLE
Banner keeps appearing on Google Chrome

### ISSUE THREAD

**Issue by AKaravas** [ghanshyamgohel/cookie_data_privacy#1]
On Safari and firefox it works perfectly. On chrome though when you press either deny or accept, the page reloads as it supposed to do, BUT the deny and accept banner, still keeps coming back and the revoke button never appears

TYPO3 Version: 8.7.15
Chrome Version: Version 67.0.3396.62 (Official Build) (64-bit)
System: MAC OS X

**Comment by ghanshyamgohel** [comment]
@AKaravas Thanks for your valuable feedback. I have tested and somehow could not found issue. Can you please show me screenshot or small video clip?

**Comment by AKaravas** [comment]
Yes of course. 
[Video Here (Youtube)](https://www.youtube.com/watch?v=tETZSwPTyU0&feature=youtu.be)

**Comment by johannnson** [comment]
I can confirm the issue on windows and linux with firefox and chrome

**Comment by ghanshyamgohel** [comment]
@johannnson 
[windows](https://www.youtube.com/watch?v=QliaErPwato) 
[working example](http://blog.typo3servers.info/)
Please check if any JS error in console.

@AKaravas possible issue [360](https://github.com/insites/cookieconsent/issues/360)

**Comment by johannnson** [comment]
Thanks @ghanshyamgohel for the Feedback.
I tricked myself and it's embarrassing. I used the wrong Domian because I used the domain of the production system on the dev system. Looks good now.
