### ISSUE TITLE
Accept without reload

### ISSUE THREAD

**Issue by FK-1991** [ghanshyamgohel/cookie_data_privacy#11]
Hello, it would be nice if in the future it would also be possible to accept cookies without reloading the page. This is not necessarily comfortable for the user. 

Many thanks for the extension. Good work!

**Comment by ghanshyamgohel** [comment]
Hallo,
Thank you for your valuable feedback. Yes, you're correct, this is annoying while accepting cookie then page reload. That concept was planned for remove JS, google analytics code from website.
Anyway, this could be done in next page refresh.

This changes will updates in next version, I'll keep you update.
Thank you,
Ghanshyam

**Comment by ghanshyamgohel** [comment]
@FK-1991 I have uploaded latest version with changes on request, Please have a look and let me know.

Thank you,
Ghanshyam

**Comment by FK-1991** [comment]
Thanks, it's working!
