### ISSUE TITLE
multilanguage support

### ISSUE THREAD

**Issue by LPGGNecromant** [ghanshyamgohel/cookie_data_privacy#12]
Within ur recent changes in the ShowCaseController.php the plugin wont support multilanguage anymore.

`Call to a member function getFormId() on null`
**in /.dtele/homepage/boehret-sehmsdorf-und-partner/public/typo3conf/ext/cookie_data_privacy/Classes/Controller/ShowCaseController.php line 71**

**Comment by ghanshyamgohel** [comment]
@LPGGNecromant I did not get time this week to check issue that you created. I shall check in next week and will updates you here.

Thank you for your patience.
Ghanshyam
