### ISSUE TITLE
TYPO3 Exception: Call to a member function getFormId() on null

### ISSUE THREAD

**Issue by hansup** [ghanshyamgohel/cookie_data_privacy#13]
@ghanshyamgohel : when the extension is fresh installed, and there are no table rows present yet, you get this exception in the front-end after including the TS template in the root ts template:
"Uncaught TYPO3 Exception
Call to a member function getFormId() on null
Error thrown in file
/ext/cookie_data_privacy/Classes/Controller/ShowCaseController.php in line 70."

TYPO3 version 8.7.28
PHP 7.2

**Comment by ghanshyamgohel** [comment]
@hansup Thank you for your feedback. This is fixed now.
