### ISSUE TITLE
BE module error when no TS include is present on the first site in the pagetree

### ISSUE THREAD

**Issue by hansup** [ghanshyamgohel/cookie_data_privacy#14]
A minor error in the Backend, but annoying when you want to add configuration.
I have a multisite installation in TYPO3 8.7.28, and after installation and including the cookie_data_pricacy (cdp) TS typoscript template on the third site-root (only the third site in the page-tree needs a cookie consent) I got this error:

"Sorry, the requested view was not found.
The technical reason is: No template was found. View could not be resolved for action "list" in class "TYPO3Liebhaber\CookieDataPrivacy\Controller\PrivacyConfigController"."

After including the cdp TS template in the *first* site TS root template, the cdp interface in the BE is shown.

**Comment by ghanshyamgohel** [comment]
@hansup I didn't get your point, can you please explain little bit more?

**Comment by ghanshyamgohel** [comment]
@hansup I have fixed this issue in latest release version, please update and let me know if anything.

[TER](https://extensions.typo3.org/extension/cookie_data_privacy)

Thank you for your support.
