### ISSUE TITLE
PrivacyConfigController::initializeView() should be compatible with TYPO3\CMS\Extbase\Mvc\Controller\ActionController::initializeView()

### ISSUE THREAD

**Issue by h4llow3En** [ghanshyamgohel/cookie_data_privacy#2]
In the PrivacyConfigController the initializeView() has to be protected and also has to accept a ViewInterface

**Comment by ghanshyamgohel** [comment]
Thank you for your valuable feedback for initializeView() should be protected not public. It's seems to me initializeView() does not need anymore. so next version will be with code improvement and code reduce.

**Comment by ghanshyamgohel** [comment]
initializeView() not needed anymore, removed!
