### ISSUE TITLE
Missing Template for List in PrivacyConfigController

### ISSUE THREAD

**Issue by h4llow3En** [ghanshyamgohel/cookie_data_privacy#3]

**Comment by ghanshyamgohel** [comment]
Did you add static template?
[documentation](https://docs.typo3.org/typo3cms/extensions/cookie_data_privacy)
[configuration](https://www.youtube.com/watch?v=QliaErPwato)

**Comment by h4llow3En** [comment]
Sorry, seems like I missed that step
