### ISSUE TITLE
Using different external scritps from google analytics does not work

### ISSUE THREAD

**Issue by h4llow3En** [ghanshyamgohel/cookie_data_privacy#5]
If you have different domains and all are tacked with google analytics and you have to include an external script, for exapmle:

Domain 1: https://www.googletagmanager.com/gtag/js?id=UA-XXXXXXXXX-1
Domain 2: https://www.googletagmanager.com/gtag/js?id=UA-XXXXXXXXX-2

The extension save this as the same script even if it is different (it overrides the last configuration)

**Comment by h4llow3En** [comment]
Maybe it would be better to use the full md5 hash instead of the fist five characters?

Edit: I tried this but there are still mixups with the different files. Maybe the problem is elsewhere

**Comment by ghanshyamgohel** [comment]
@h4llow3En should be work now

**Comment by h4llow3En** [comment]
There are still some mixups.
In my case I saved the first one and the file was created. Then I saved the second one and both entries were changed to the second saved script. (The filecontent of the first one also changed)

Somehow I managed to get the right scripts. But across all domains only on script is included (in my case always from the last configuration)

**Comment by ghanshyamgohel** [comment]
@h4llow3En found issue, TS override in multi-domain. now each domain has separate TS for include external js/css. Please check and confirm if fix issue. Thank you!
