### ISSUE TITLE
Extension prevents some forms from being sent

### ISSUE THREAD

**Issue by JakoD** [ghanshyamgohel/cookie_data_privacy#8]
The script embedded in Templates/ShowCase/Show.html prevents forms with `id` or `name` attributes from being sent.
This happens, because for forms with those attributes, after checking some checkbox states and toggling some elements, `false` is returned, canceling the event.
Forms built with the TYPO3 form framework have their form identifier set as id attribute, so this behavior applies for them too.

A minimal form may produce html similar to:
```
<form enctype="multipart/form-data" method="post" class="form" id="test" action="/?tx_form_formframework%5Baction%5D=perform&amp;tx_form_formframework%5Bcontroller%5D=FormFrontend&amp;cHash=<cHash>#test">
    <div>
        <input name="tx_form_formframework[test][__state]" value="<some form state>" type="hidden">
        <input name="tx_form_formframework[__trustedProperties]" value="<the trusted properties>" type="hidden">
    </div>
    <h2>Step</h2>
    <input autocomplete="off" id="test-eWzFGKMyPQoJIN" style="position:absolute; margin:0 0 0 -999em;" tabindex="-1" name="tx_form_formframework[test][eWzFGKMyPQoJIN]" type="text">
    <div class="form-group">
        <label class="control-label" for="test-text-1">
            Enter your name<span class="required">*</span>
        </label>
        <div class="input">
            <input required="required" class=" form-control" id="test-text-1" name="tx_form_formframework[test][text-1]" value="" type="text">
        </div>
    </div>
    <div class="actions">
        <nav class="form-navigation">
            <div class="btn-toolbar" role="toolbar">
                <div class="btn-group" role="group">
                    <span class="next submit">
                        <button class="btn btn--primary" type="submit" name="tx_form_formframework[test][__currentPage]" value="1">
                            Absenden
                        </button>
                    </span>
                </div>
            </div>
        </nav>
    </div>
</form>
```

**Comment by ghanshyamgohel** [comment]
GDPR said form must have checkbox which should not checked by-default. User must check checkbox which have accept proceed form before submit.
[documentation](https://docs.typo3.org/typo3cms/extensions/cookie_data_privacy/Introduction/Index.html)
[YouTube](https://www.youtube.com/watch?v=QliaErPwato)

**Comment by JakoD** [comment]
The example form was intended to show the general structure, and that it doesn't match the structure requested by the script. (maybe I should have included a checkbox and also state this more clearly before ...).
Making the form framework match the structure would require either to:
- change the form framework frontend templates and also the form editor backend configuration for checkboxes
- add custom form elements with own templates (recommended way)

Also not every form necessarily requires those fields (e.g. a form for changing the password within the user's account page) or deals with personal data at all.

My suggestion would be to add a setting to disable this automatic check, but keeping it enabled by default. This way developers could re-implement that behavior for their forms needs without losing the complete extension functionality.
A long-term feature could be adding the necessary form element(s) for the form framework and always setting the required attribute on them.

**Comment by ghanshyamgohel** [comment]
@JakoD thank you for your valuable feedback, I got issue and fix it with latest version. now you have [option](https://www.screencast.com/t/zZIlr62kuN) to add form IDs from backend for required data privacy.
